'use strict';
const bill = [
  {
    title: 'Efficient Use of Government Spectrum Act of 2013',
    billNumber: 'hr2739-113',
    url: 'https://www.congress.gov/bill/113th-congress/house-bill/2739',
    sponsorName: 'Doris Matsui',
    sponsorId: 'M001163',
    sponsorParty: 'D',
    introduced: '2013-07-18',
    active: false,
    committees: 'House Armed Services Committee',
    primarySubject: 'Science, Technology, Communications',
    summary:'',
    summaryShort:'',
    latestActionDate: '2013-08-29',
    latestAction:'Referred to the Subcommittee on Intelligence, Emerging Threats &amp; Capabilities.',
    userId: 1,
    categoryId: 2,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Wireless Innovation Act of 2014',
    billNumber: 's2473-113',
    url: 'https://www.congress.gov/bill/113th-congress/senate-bill/2473',
    sponsorName: 'Marco Rubio',
    sponsorId: 'R000595',
    sponsorParty: 'R',
    introduced: '2014-06-12',
    active: false,
    committees: 'House Armed Services Committee',
    primarySubject: 'Science, Technology, Communications',
    summary:'',
    summaryShort:'',
    latestActionDate: '2014-06-12',
    latestAction:
      'Read twice and referred to the Committee on Commerce, Science, and Transportation.',
      userId: 2,
      categoryId: 2,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title:
      'Reducing Employer Burdens, Unleashing Innovation, and Labor Development Act of 2013',
    billNumber: 'hr3355-113',
    url: 'https://www.congress.gov/bill/113th-congress/house-bill/3355',
    sponsorName: 'Brett Guthrie',
    sponsorId: 'G000558',
    sponsorParty: 'R',
    introduced: '2013-10-28',
    active: false,
    committees: 'House Armed Services Committee',
    primarySubject: 'Economics and Public Finance',
    summary:'',
    summaryShort:'',
    latestActionDate: '2014-01-24',
    latestAction:
      'Referred to the Subcommittee on Intelligence, Emerging Threats &amp; Capabilities.',
      userId: 3,
      categoryId: 9,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'Promoting Unlicensed Spectrum Act of 2015',
    billNumber: 's2278-114',
    url: 'https://www.congress.gov/bill/114th-congress/senate-bill/2278',
    sponsorName: 'Brian Schatz',
    sponsorId: 'S001194',
    sponsorParty: 'D',
    introduced: '2015-11-10',
    active: false,
    committees: 'Senate Commerce, Science, and Transportation Committee',
    primarySubject: 'Science, Technology, Communications',
    summary:'',
    summaryShort:'',
    latestActionDate: '2015-11-10',
    latestAction:
      'Read twice and referred to the Committee on Commerce, Science, and Transportation.',
      userId: 4,
      categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date()
  },
  {
    title: 'MOBILE NOW Act',
    billNumber: 's2555-114',
    url: 'https://www.congress.gov/bill/114th-congress/senate-bill/2555',
    sponsorName: 'John Thune',
    sponsorId: 'T000250',
    sponsorParty: 'R',
    introduced: '2016-02-11',
    active: true,
    committees: 'Senate Commerce, Science, and Transportation Committee',
    primarySubject: 'Science, Technology, Communications',
    summary:'',
    summaryShort:'',
    latestActionDate: '2016-12-20',
    latestAction:
      'By Senator Thune from Committee on Commerce, Science, and Transportation filed written report under authority of the order of the Senate of 12/10/2016. Report No. 114-427.',
      userId: 4,
      categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date()
  },
  {
    title: 'Wireless Innovation Act of 2015',
    billNumber: 's1618-114',
    url: 'https://www.congress.gov/bill/114th-congress/senate-bill/1618',
    sponsorName: 'Marco Rubio',
    sponsorId: 'R000595',
    sponsorParty: 'R',
    introduced: '2015-06-18',
    active: 'false',
    committees: 'Senate Commerce, Science, and Transportation Committee',
    primarySubject: 'Science, Technology, Communications',
    summary: '',
    summaryShort:'',
    latestActionDate: '2015-06-18',
    latestAction:
      'Read twice and referred to the Committee on Commerce, Science, and Transportation.',
      userId: 5,
      categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date()
  },
  {
    title: 'FCC Reauthorization Act of 2016',
    billNumber: 's2644-114',
    url: 'https://www.congress.gov/bill/114th-congress/senate-bill/2644',
    sponsorName: 'John Thune',
    sponsorId: 'T000250',
    sponsorParty: 'R',
    introduced: '2016-03-07',
    active: true,
    committees: 'Senate Commerce, Science, and Transportation Committee',
    primarySubject: 'Science, Technology, Communications',
    summary:'',
    summaryShort:'',
    latestActionDate: '2016-09-20',
    latestAction:
      'Placed on Senate Legislative Calendar under General Orders. Calendar No. 637.',
      userId: 1,
      categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date()
  },
  {
    title: 'Bipartisan Budget Act of 2015',
    billNumber: 'hr1314-114',
    url: 'https://www.congress.gov/bill/114th-congress/house-bill/1314',
    sponsorName: 'Pat Meehan',
    sponsorId: 'M001181',
    sponsorParty: 'R',
    introduced: '2015-03-04',
    active: true,
    committees: 'House Ways and Means Committee',
    primarySubject: 'Economics and Public Finance',
    summary:'',
    summaryShort:'',
    latestActionDate: '2015-11-02',
    latestAction: 'Became Public Law No: 114-74.',
    userId: 2,
    categoryId: 9,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: 'MOBILE NOW Act',
    billNumber: 's19-115',
    url: 'https://www.congress.gov/bill/115th-congress/senate-bill/19',
    sponsorName: 'John Thune',
    sponsorId: 'T000250',
    sponsorParty: 'R',
    introduced: '2017-01-03',
    active: true,
    committees: 'Senate Commerce, Science, and Transportation Committee',
    primarySubject: 'Science, Technology, Communications',
    summary:'',
    summaryShort:'',
    latestActionDate: '2017-03-21',
    latestAction:
      'Placed on Senate Legislative Calendar under General Orders. Calendar No. 17.',
      userId: 3,
      categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date()
  },
  {
    title: 'Coast Guard Authorization Act of 2017',
    billNumber: 's1129-115',
    url: 'https://www.congress.gov/bill/115th-congress/senate-bill/1129',
    sponsorName: 'Dan Sullivan',
    sponsorId: 'S001198',
    sponsorParty: 'R',
    introduced: '2017-05-16',
    active: true,
    committees: 'Senate Commerce, Science, and Transportation Committee',
    primarySubject: 'Public Lands and Natural Resources',
    summary: '',
    summaryShort: '',
    latestActionDate: '2017-06-05',
    latestAction:
      'Placed on Senate Legislative Calendar under General Orders. Calendar No. 112.',
      userId: 4,
      categoryId: 10,
      createdAt: new Date(),
      updatedAt: new Date()
  },
  {
    title: 'FCC Reauthorization Act of 2016',
    billNumber: 's2644-114',
    url: 'https://www.congress.gov/bill/114th-congress/senate-bill/2644',
    sponsorName: 'John Thune',
    sponsorId: 'T000250',
    sponsorParty: 'R',
    introduced: '2016-03-07',
    active: true,
    committees: 'Senate Commerce, Science, and Transportation Committee',
    primarySubject: 'Science, Technology, Communications',
    summary:'',
    summaryShort:'',
    latestActionDate: '2016-09-20',
    latestAction:
      'Placed on Senate Legislative Calendar under General Orders. Calendar No. 637.',
      userId: 5,
      categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date()
  },



];

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('bills', bill, {});
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('bills', null, {});
  }
};
